[project]
name = "mywagtailsite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dj-database-url>=3.0.1",
    "django>=5.2,<5.3",
    "gunicorn>=23.0.0",
    "psycopg[binary]>=3.3.2",
    "wagtail>=7.2,<7.3",
]
